### ISSUE TITLE
Failure to find com.fasterxml.jackson.core:jackson-databind:jar:2.7.8

### ISSUE THREAD

**Issue by jzhuge** [cloudera/dist_test#36]
Sync to commit aa0076e038ea79d61208b2f8d10a3f7f379117cd, got error:

> $ grind test -m hadoop-kms
> INFO:root:Read config from location /Users/jzhuge/.grind/grind.cfg
> INFO:root:Read config from location /Users/jzhuge/hadoop/.grind_project.cfg
> INFO:disttest.isolate:Using output directory /Users/jzhuge/.grind/temp/grind.j0mm1f
> INFO:root:Found 1 included modules out of 76 total modules with 5 test classes within project /Users/jzhuge/hadoop/
> INFO:disttest.packager:Packaged 76 modules to output directory /Users/jzhuge/.grind/temp/grind.j0mm1f
> INFO:disttest.packager:No matching cached dependency set found for path /Users/jzhuge/hadoop/ manifest None, regenerating
> INFO:disttest.packager:Removing stale cached dependency set at /Users/jzhuge/.grind/cache/Users/jzhuge/hadoop/
> INFO:disttest.packager:Detecting environment mvn via `. /Users/jzhuge/.grind/cache/Users/jzhuge/hadoop/environment.source; which mvn`
> INFO:disttest.packager:Invoking `/Users/jzhuge/.grind/cache/Users/jzhuge/hadoop/apache-maven-3.3.3/bin/mvn  --settings /Users/jzhuge/.grind/cache/Users/jzhuge/hadoop/settings.xml -q dependency:copy-dependencies -Dmdep.useRepositoryLayout=true -Dmdep.copyPom -Dmdep.addParentPoms -DoutputDirectory=/Users/jzhuge/.grind/cache/Users/jzhuge/hadoop/.m2/repository `
> [ERROR] Failed to execute goal on project hadoop-maven-plugins: Could not resolve dependencies for project org.apache.hadoop:hadoop-maven-plugins:maven-plugin:3.0.0-alpha2-SNAPSHOT: Failure to find com.fasterxml.jackson.core:jackson-databind:jar:2.7.8 in https://repository.apache.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots.https has elapsed or updates are forced -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :hadoop-maven-plugins
> Traceback (most recent call last):
>   File "/Users/jzhuge/dist_test/bin/grind", line 597, in <module>
>     main()
>   File "/Users/jzhuge/dist_test/bin/grind", line 574, in main
>     subcommands[args.subparser_name](config, args)
>   File "/Users/jzhuge/dist_test/bin/grind", line 588, in test_subcommand
>     runner.run()
>   File "/Users/jzhuge/dist_test/bin/grind", line 383, in run
>     self.run_tests()
>   File "/Users/jzhuge/dist_test/bin/grind", line 407, in run_tests
>     i.package()
>   File "/Users/jzhuge/dist_test/grind/python/disttest/isolate.py", line 81, in package
>     self.packager.package_all()
>   File "/Users/jzhuge/dist_test/grind/python/disttest/packager.py", line 400, in package_all
>     self._package_maven_dependencies()
>   File "/Users/jzhuge/dist_test/grind/python/disttest/packager.py", line 383, in _package_maven_dependencies
>     self._regenerate_dependency_cache_if_necessary()
>   File "/Users/jzhuge/dist_test/grind/python/disttest/packager.py", line 319, in _regenerate_dependency_cache_if_necessary
>     self._regenerate_dependency_cache()
>   File "/Users/jzhuge/dist_test/grind/python/disttest/packager.py", line 358, in _regenerate_dependency_cache
>     Packager.__shell(cmd, self.__project_root)
>   File "/Users/jzhuge/dist_test/grind/python/disttest/packager.py", line 375, in __shell
>     raise Exception("Error while invoking %s" % cmd)
> Exception: Error while invoking /Users/jzhuge/.grind/cache/Users/jzhuge/hadoop/apache-maven-3.3.3/bin/mvn  --settings /Users/jzhuge/.grind/cache/Users/jzhuge/hadoop/settings.xml -q dependency:copy-dependencies -Dmdep.useRepositoryLayout=true -Dmdep.copyPom -Dmdep.addParentPoms -DoutputDirectory=/Users/jzhuge/.grind/cache/Users/jzhuge/hadoop/.m2/repository

**Comment by jzhuge** [comment]
This only happens to Hadoop trunk. CDH is fine.
