### ISSUE TITLE
grind test --list-modules broken

### ISSUE THREAD

**Issue by xiao-chen** [cloudera/dist_test#43]
Haven't investigated, but seems this basically is broken.
```-bash-4.2$ grind test -l
INFO:Read config from location /home/xiao/.grind/grind.cfg
INFO:No ProjectConfig configuration file found, using defaults.
Traceback (most recent call last):
  File "/home/xiao/flakyserver/dist_test/bin/grind", line 608, in <module>
    main()
  File "/home/xiao/flakyserver/dist_test/bin/grind", line 585, in main
    subcommands[args.subparser_name](config, args)
  File "/home/xiao/flakyserver/dist_test/bin/grind", line 599, in test_subcommand
    runner.run()
  File "/home/xiao/flakyserver/dist_test/bin/grind", line 385, in run
    i = isolate.Isolate(self.project_dir, self.output_dir, include_modules=[])
TypeError: __init__() takes at least 4 arguments (4 given)```

**Comment by jzhuge** [comment]
1fc84a8e8fd9be91a93982b913b87958f0a86da5 broke it

**Comment by xiao-chen** [comment]
@toddlipcon @umbrant , John's https://github.com/cloudera/dist_test/pull/52 looks to be fixing this. Can we pull it in?
